name: publish dp deezer
on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 20
                registry-url: https://registry.npmjs.org/
            - run: yarn npm:publish
              env:
                NODE_AUTH_TOKEN: ${{secrets.npm_token}}
